### ISSUE TITLE
track: issues with Policies created through Operator in Tyk Dashboard

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-operator#114]
1.  Created policies don't allow you to create keys through UI
2.  Created policies don't allow you to publish them to the Portal

These are being addressed in a Tyk Dashboard issue.  This will become the minimum Dashboard version to use with the Operator

**Comment by letzya** [comment]
@asoorm what is the reason for this bug? is it related to mongo object ids and policy id?

**Comment by sedkis** [comment]
> @asoorm what is the reason for this bug? is it related to mongo object ids and policy id?

Correct.  It's been addressed in a Dashboard ticket and should be released `v3.1.1`

**Comment by gernest** [comment]
@sedkis do you have the link to the PR that fixes this? What was the issue?

**Comment by sedkis** [comment]
https://github.com/TykTechnologies/tyk/releases/tag/v3.1.1

> Fix APIs and Policies synchronization when using Tyk Sync. Should be used together with Tyk Sync 1.2
This incorrectly states Tyk Sync only.  That fix allows for Tyk-Operator to be used as well
