### ISSUE TITLE
feat: cut a release

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#191]
https://github.com/TykTechnologies/tyk-operator/actions?query=workflow%3A%22Cut+Release%22

https://github.com/TykTechnologies/tyk-operator/blob/master/.github/workflows/cut_release.yml

We have a new GitHub action - called cut_release.

It is triggered manually from GitHub Actions.

![Screenshot 2020-12-02 at 13 41 04](https://user-images.githubusercontent.com/1465130/100880494-b6bc3280-34a4-11eb-8f20-67518f3167b9.png)

We specify the version of the release we want to cut - and apply that to the master branch.

When we manually trigger the release, the action should:

- [ ] Change the tagged version in the helm chart.yaml https://github.com/TykTechnologies/tyk-operator/blob/master/helm/Chart.yaml#L5
- [ ] Tag the master branch & push the tags.

This will trigger a goreleaser github action / build pipeline to push to Dockerhub - once master branch is pushed.

---

The current flow is a little manual & as such, if i forget to bump the Chart.yaml or something - then my release is broken.

**Comment by buger** [comment]
Love it. 

@alephnull smth we talked about in context of manually running Github actions

**Comment by alephnull** [comment]
To make sure I understand,
- I specify a version tag on the github UI (Release tag)
- The action then applies the tag I just specified into Charts.yaml and commits the change
- Then the existing goreleaser will take over

Have I got it right?

**Comment by asoorm** [comment]
@alephnull that sounds perfect.

It may be better to just apply this logic to GoReleaser action anyway? I'll leave it to you to decide.

**Comment by alephnull** [comment]
> It may be better to just apply this logic to GoReleaser action anyway?
Yup, that's what I was thinking of doing. I'll remove the cut_release action.
