### ISSUE TITLE
Upgrade operator-sdk to v1.3.0

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#220]
https://github.com/operator-framework/operator-sdk/releases/tag/v1.3.0

This will unblock various capabilities including:

* Kubernetes v1.19 support
* v1 CRD and webhook configuration support by default
* Liveness and readiness probes
* An option to use controller-runtime's component config to configure your operator

[upgrade guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.3.0/)

@excieve FYI

**Comment by asoorm** [comment]
This is currently blocked - as upgrading Operator SDK to 1.3 potentially means forcing customers to upgrade to Kubernetes v1.19 - which would be unrealistic. Requires further research.

**Comment by gernest** [comment]
done #316
