### ISSUE TITLE
api ids should be deterministic

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#231]
3 use cases which Tyk Operator was designed for:

1. Migrate from Tyk CE to Tyk Pro
2. Backup & Restore (disaster recovery)
3. Ability to upgrade operator versions

All above should work without keys stopping working.

---

The API ID was designed to be deterministic `base64(namespace/name)`.

1. create protected API
2. create key granting access to that API
3. delete API
4. key stops working
5. re-create the API
6. key should continue working again.

---

The Policy was also designed to be deterministic. 

Currently works, but must continue working

1. create protected API
2. create a policy granting access to that API
3. create key granting access to that policy
4. delete policy
5. key stops working
6. re-create the policy
6. key should continue working again.

---

When customers upgrade from 0.1 to 0.2, at the moment, their keys will all stop working because apiid will change from b64encoded namespace/name to mongo ids.

**Comment by asoorm** [comment]
https://user-images.githubusercontent.com/1465130/103415141-c3ea4100-4b78-11eb-9850-bfc4317d9c0c.mp4

**Comment by sedkis** [comment]
This is crucial functionality

**Comment by asoorm** [comment]
We need to setup BDD tests for this logic too.
