### ISSUE TITLE
Support for updating the API Catalog

### ISSUE THREAD

**Issue by FAntonescu** [TykTechnologies/tyk-operator#266]
## Expected Behavior
As an API developer I would like to have the ability to have the OpenAPI documentation managed by the Tyk Operator

## Current Behavior
Currently the Tyk Operator does not support updating the API Catalog.
The only way to update the Swagger documentation is by manually removing and then adding the documentation in the Tyk Dashboard.

## Possible Solution
Add the possibility to link in the API Definition to a config map containing the Swagger specification.

**Comment by asoorm** [comment]
https://github.com/TykTechnologies/tyk-operator/pull/290
