### ISSUE TITLE
Version apiextensions.k8s.io/v1beta1:CustomResourceDefinition is deprecated

### ISSUE THREAD

**Issue by illinar** [TykTechnologies/tyk-operator#273]
CRDs are still using v1beta1 version which is deprecated since 1.16 and will become unavailable at 1.22.

## Expected Behavior
CRDs should use v1 version instead.

**Comment by illinar** [comment]
Similar situation with ValidatingWebhookConfiguration

**Comment by gernest** [comment]
this has been addressed in #316
