### ISSUE TITLE
tyk-operator-conf???

### ISSUE THREAD

**Issue by tirelibirefe** [TykTechnologies/tyk-operator#362]
Hello,
Documentation is missing.
How and from where can I get these information?

TYK_ORG
TYK_AUTH
TYK_MODE
TYK_URL
WATCH_INGRESS_CLASS
TYK_HTTPS_INGRESS_PORT
TYK_HTTP_INGRESS_PORT

Regards

**Comment by tyktestytyk** [comment]
Hi Tireli

Good to hear from you.

It seems that this issue you have raised are related to Tyk installation & Docs and not specifically Tyk Operator code.  

We can also see that you have asked the same questions on Tyk Community Forum: https://community.tyk.io/t/tyk-operator-parameters/4896 

This is certainly the best place to ask these types of Installation & Docs related questions. Expect to have receive a response within 2 business days.

You could also have a look at our Helm Chart Repo
https://github.com/TykTechnologies/tyk-helm-chart/

Thanks for your feedback

**Comment by asoorm** [comment]
Closing as appears to not be a defect with Operator and seems to be related to Tyk documentation issue.
