### ISSUE TITLE
how can I access to tyk dashboard? Missing documentation.

### ISSUE THREAD

**Issue by tirelibirefe** [TykTechnologies/tyk-operator#363]
Hello,
I've installed tyk gw.
Ingress doesn't work. When I enable ingress, it gives 503 error. So I disabled ingress and now Its service is nodeport.
How can I administrate tyk gw?

Regards

**Comment by tyktestytyk** [comment]
Hello Tireli
Thanks for getting in touch.
We can see that you have posted similar questions on Tyk Community Forum.
This is definitely the best place to ask these types of questions. Expect a response on Community within 2 business days

**Comment by asoorm** [comment]
Closing as appears to not be a defect and seems to have been resolved in community forum.
