### ISSUE TITLE
aws nlb

### ISSUE THREAD

**Issue by tirelibirefe** [TykTechnologies/tyk-operator#364]
Hello,
I couldn't have any documentation regarding to AWS NLB compatilibty.
Can tyk ingress work with AWS NLB as LoadBalancer? If I want to terminate ssl at aws nlb level, is it necessary installing cert-manageR?

**Comment by tyktestytyk** [comment]
Hello Tireli
Thanks for getting in touch.
In the past we can see that you have posted similar questions on Tyk Community Forum.  
This is definitely the best place to ask these types of questions. Expect a response on Community within 2 business days

**Comment by asoorm** [comment]
Closing as appears to not be a defect and seems to have been resolved in community forum.
