### ISSUE TITLE
[TT-4615] environmet.Env.Parse doesnt return errors on bad data

### ISSUE THREAD

**Issue by oneEyedSunday** [TykTechnologies/tyk-operator#392]
⚠️ ⚠️ ⚠️
environmet.Env.Parse is [documented](https://github.com/TykTechnologies/tyk-operator/blob/master/pkg/environmet/env.go#L54) as returning errors on failure to validate. 
In reality, it doesn't return an error and callers have to further validate by themselves see [1](https://github.com/TykTechnologies/tyk-operator/blob/0e375ab624ede891f558f91d18e5aa6a527eddb0/integration/main_test.go#L31), [2](https://github.com/TykTechnologies/tyk-operator/blob/13b83ecc672e22b94aa8c07bf8dcef97029d6107/main.go#L70)

⚠️ ⚠️ ⚠️

## Expected Behavior
environmet.Env.Parse docs should remove phrases insinuating that it returns errors on validation.

## Additional Context
Current behaviour will remain unchanged.
At some point in the past, it did return errors, [see](https://github.com/TykTechnologies/tyk-operator/blame/f0058f1893e984034babe76e9ba250e63225e81f/pkg/environmet/env.go)

**Comment by buraksekili** [comment]
@oneEyedSunday thank you for raising this issue! We will check for potential fixes for it. Let's keep this issue open until then. Again, thanks!

**Comment by tzzed** [comment]
It seems there is typo in the package name `environmet` which should probably be `environment`.

**Comment by oneEyedSunday** [comment]
Well at this point that's basically a feature. It's ingrained into the
whole application

**Comment by caroltyk** [comment]
Thank you for raising this issue to us. The fix will be available in release 0.15.1
