### ISSUE TITLE
[TT-5181] - Client to Gateway Authentication mTLS support

### ISSUE THREAD

**Issue by SudhakarNandigam-TomTom** [TykTechnologies/tyk-operator#447]
I see in [API Definitions](https://github.com/TykTechnologies/tyk-operator/blob/master/docs/api_definitions.md), Client to Gateway Authentication mTLS is not implemented status. Is there a plan to implement it?

**Comment by caroltyk** [comment]
Hi @SudhakarNandigam-TomTom , thank you for your query.

Currently, we prioritise our feature roadmap based on customer demand. So raising requests here would definitely help. Could you let us know more about your use case?

**Comment by SudhakarNandigam-TomTom** [comment]
A kubernetes secret containing the CA certificate, Server Certificate (Signed by CA), and Private key is supplied to the Tyk gateway which can be used for both TLS and Client Auth. The client will then use the CA certificate, Client Certificate (Signed by CA) and Key to authenticate with the gateway.
Also enable Certificate Revocation List verification.
