### ISSUE TITLE
[TT-7086] Add hostNetwork option in helm chart

### ISSUE THREAD

**Issue by rdcwaldrop1** [TykTechnologies/tyk-operator#532]
## Expected Behavior

Given our current ENI Configuration in Amazon EKS we need to run the Tyk Operator deployment with hostNetwork mode set to true.  I'd like to be able to specify this as a boolean toggle in the values file.

### Potential BDD Test Coverage

```gherkin
Feature: hostNetwork Mode
  As a developer
  I want to enable hostNetwork mode for the deployment
  So that I can install Tyk Operator in my EKS cluster

  Scenario: hostNetwork mode enabled
    Given that .Values.hostNetwork = true
    When I deploy Tyk Operator
    Then the associated pods run with hostNetwork mode enabled
```

## Current Behavior

The current helm chart provides no means to update the hostNetwork value so I am unable to configure this without editing the underlying template.  I'd like to bring this chart in as a helm dependency and not have to edit the template. 

## Possible Solution

A small block could be added [here](https://github.com/TykTechnologies/tyk-operator/blob/6f4c531a58486ef8786a6a4c6577354a2bfe89b2/helm/templates/all.yaml#L418) to set hostNetwork mode equal to .Values.hostNetwork mode or a default of false

```yaml
      hostNetwork:  {{ .Values.hostNetwork | default false }}
```

**Comment by komalsukhani** [comment]
Thank you for raising this issue @rdcwaldrop1! I will add this ticket in our backlog and keep you posted about it's progress.

We also welcome community PRs in case you are interested!

**Comment by rdcwaldrop1** [comment]
> Thank you for raising this issue @rdcwaldrop1! I will add this ticket in our backlog and keep you posted about it's progress.
> 
> We also welcome community PRs in case you are interested!

Great! Thanks @komalsukhani. I'd be happy to take a crack at a PR to add this.

**Comment by rdcwaldrop1** [comment]
I've added a [draft PR](https://github.com/TykTechnologies/tyk-operator/pull/537) with my thinking on the change to enable hostNetwork mode.  The PR template asks to describe testing, but I'm not seeing any automated tests in the repo for helm.  Typically how is testing for helm changes handled in this repo? Is there a better place to ask this question?

**Comment by buraksekili** [comment]
@rdcwaldrop1 you are right, we do not have any testing for helm changes for tyk-operator yet. You can create your PR and once your PR is approved, we can test your PR internally and then merge it.

**Comment by rdcwaldrop1** [comment]
Thanks @buraksekili for your feedback here and on the PR.  I'll take a look at the process you explained and update the PR accordingly.  🙇
