### ISSUE TITLE
Allow policies to be filtered by associated API category while using snapshot

### ISSUE THREAD

**Issue by zalbiraw** [TykTechnologies/tyk-operator#592]
As a user I would like to only export the security policies associated with the APIs I am looking to export. 

For larger and more in-depth feature requests, please consider [starting an RFC thread](https://github.com/TykTechnologies/tyk-operator/discussions/new)
in the [Discussions area](https://github.com/TykTechnologies/tyk-operator/discussions) of this project.

⚠️ ⚠️ ⚠️

## Expected Behavior
Filter policies by `--category` flag

### Potential BDD Test Coverage

```gherkin
Feature: <summary of feature>
  As a developer
  I want to export my API definitions and security policies while filtering by category
  So that I can have a more specific export of CRDs

  Scenario: <summary of a scenario within this feature>
    Given <context>
    When <event occurs>
    Then <outcome>
```

## Current Behavior

All policies are exported

**Comment by caroltyk** [comment]
Since a policy may contain API Definitions from another category, if we export policies with APIs not present in k8s, that could lead to error. Maybe we can use the generic metadata tag to categorise policies instead, and export APIs and Policies separately.
