### ISSUE TITLE
Gateway loses all APIDefinitions and Policies if the gateway is restarted

### ISSUE THREAD

**Issue by utkarsh079** [TykTechnologies/tyk-operator#659]
In case if the gateway (headless, installed with helm) is restarted, all APIDefinitions and Policies are deleted even though the APIDefinition and Policies resources are still there. I understand that the gateway keeps the APIDefinition and Policies at '/mnt/tyk-gateway/apps' and '/mnt/tyk-gateway/policies' which obviously gets deleted once the pod is restarted. But this natural to assume that operator-controller would recreate the object is gateway if it gets 404 from gateway.

## Expected Behavior
APIDefinition, Policy, etc objects should be re-pushed into gateway in case operator gets 404 but the Custom resource exists.

## Current Behavior
Operator does not recreate the objects into gateway. have to delete the APIDefinition and policy resources from kubernetes and then needs to be recreated

## Steps to Reproduce
For example:
1. Create an APIDefinition
2. Restart gateway pods
3. You will get 404 for that API even though the APIDefinition exists

**Comment by buraksekili** [comment]
Hi @utkarsh079, thank you for bringing this up and for using Tyk Operator. This behavior is actually an expected functionality while using the Tyk Operator. Let me provide a brief explanation of the Operator pattern.

We employ a Kubernetes Controller, known as Tyk Operator, to synchronize the state between Kubernetes and Tyk Gateway. However, it's important to note that Tyk Operator is triggered solely by changes in Kubernetes, not within Tyk itself. This means Tyk Operator does not actively listen for changes within the Tyk Gateway; rather, it responds to changes in Kubernetes Resources. You can find more details in our documentation here: [Tyk Operator Reconciliation](https://tyk.io/docs/tyk-stack/tyk-operator/tyk-operator-reconciliation/).

Regarding the scenario you've shared, in the next reconciliation cycle, your APIDefinitions will be created within Tyk as well. To test this, a simple restart of the Tyk Operator pod should suffice. Upon restart, the Operator will recognize that the Kubernetes Custom resource is absent in the Tyk Gateway and will create it accordingly.

Please let me know if I can clarify further or if you encounter any issues. If necessary, we can delve deeper into the investigation. Thanks once again!

**Comment by utkarsh079** [comment]
Thats interesting. What is the recommended way of keeping the installation of tyk-gateway and ty-operator in that case?
I mean it is not possible to redeploy each CR again with kubernetes whenever there is a restart (planned or unplanned) in gateway.
Only option I can think of is to restart tyk-operator everytime whenever there is suchevent. Its not ideal bit that what I can think of.

**Comment by caroltyk** [comment]
Closing this issue as not a defect.
