### ISSUE TITLE
policies (feat req): API level limits

### ISSUE THREAD

**Issue by sedkis** [TykTechnologies/tyk-operator#66]
requesting the ability to add per API level limits into a SecurityPolicy declaratively.

Here's a screenshot from the Tyk Dashboard that illustrates this.
![image](https://user-images.githubusercontent.com/8964621/95216692-5ec4c080-07c0-11eb-926c-a1a828387572.png)

This functionality allows you to do per API limits in a policy.
[Here's the field](https://github.com/TykTechnologies/tyk-operator/blob/master/api/v1alpha1/securitypolicy_types.go#L89) that needs to be enabled to allow this to happen.

**Comment by gernest** [comment]
`partitions` is already enabled in `SecurityPolicySpec`
