### ISSUE TITLE
research: how to package & deploy the Tyk Operator

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#91]
There are many ways in which an operator can be deployed into a cluster:

- ~YAMLs~
- ~Operator Lifecycle Manager~ OpenShift specific
- Kustomize
- Helm

Maybe at some stage, we will support them all, however for MVP, we need to pick a method & prioritise order in which we will introduce each deployment method.

Would be great to get some voting in place to understand priorities.

---

Helm seems the obvious solution, however it is not without it's pitfalls: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations

> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.

**Comment by drpebcak** [comment]
A somewhat common approach for CRDs with helm is to publish releases of the CRDs to be used with `kubectl apply -f` (pointing at a specific version of the artifact on github), and then the rest of the resources are installed by the helm chart once that is done.
